Follow the error given in Windows debug death test "')' is unsupported"
D:\a\egoa\egoa\external\GoogleTestFramework\googletest\src/gtest-port.cc(844): error: Failed
1: Syntax error at index 42 in simple regular expression "(.*) assertion failed at (.*)Bound.hpp:(.*) inside Bound.
1:  Condition: minimum_ <= maximum_": ')' is unsupported.
1:
1: Running main() from D:\a\egoa\egoa\external\GoogleTestFramework\googletest\src\gtest_main.cc
1: D:\a\egoa\egoa\tests\DataStructures\TestBound.cpp(70): error: Death test: {egoa::Bound<> bound (3,1);}
1:     Result: died but not with expected error.
1:   Expected: contains regular expression "(.*) assertion failed at (.*)Bound.hpp:(.*) inside Bound.\n Condition: minimum_ <= maximum_"
1: Actual msg:
1: [  DEATH   ] USAGE assertion failed at D:\a\egoa\egoa\include\DataStructures/Bound.hpp:48 inside egoa::Bound<double>::Bound.
1: [  DEATH   ]  Condition: minimum_ <= maximum_
1:
1: [  FAILED  ] TestBound.DeathTest (146 ms)

Changes to be committed:
	modified:   tests/Helper/TestHelper.hpp