The output differs in "inside Bound.\n Condition" from "inside egoa::Bound<double>::Bound.\n Condition".
 D:\a\egoa\egoa\tests\DataStructures\TestBound.cpp(70): error: Death test: {egoa::Bound<> bound (3,1);}
1:     Result: died but not with expected error.
1:   Expected: contains regular expression ".* assertion failed at .*Bound.hpp:.* inside Bound.\n Condition: minimum_ <= maximum_"
1: Actual msg:
1: [  DEATH   ] USAGE assertion failed at D:\a\egoa\egoa\include\DataStructures/Bound.hpp:48 inside egoa::Bound<double>::Bound.
1: [  DEATH   ]  Condition: minimum_ <= maximum_

Changes to be committed:
	modified:   tests/Helper/TestHelper.hpp