Change from std::input_iterator_tag to std::forward_iterator_tag (#31)
This switch is done due to the error we get within the Bucket tests that basically does not allow a conversion from std::input_iterator to std::forward_iterator, i.e.,  error: static assertion failed due to requirement '__has_iterator_category_convertible_to<egoa::BinaryHeap<egoa::BucketElement<long long>>::HeapIterator, std::forward_iterator_tag, true>::value': std::min_element requires a ForwardIterator.

See the below message for more information:

/opt/homebrew/opt/llvm/bin/../include/c++/v1/__algorithm/min_element.h:55:17: error: static assertion failed due to requirement '__has_iterator_category_convertible_to<egoa::BinaryHeap<egoa::BucketElement<long long>>::HeapIterator, std::forward_iterator_tag, true>::value': std::min_element requires a ForwardIterator
   55 |   static_assert(__has_forward_iterator_category<_ForwardIterator>::value,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/fwegner/Documents/Repositories/Public/EGOA/egoa/include/DataStructures/Container/Queues/Bucket.hpp:339:37: note: in instantiation of function template specialization 'std::min_element<egoa::BinaryHeap<egoa::BucketElement<long long>>::HeapIterator, (lambda at /Users/fwegner/Documents/Repositories/Public/EGOA/egoa/include/DataStructures/Container/Queues/Bucket.hpp:339:108)>' requested here
  339 |                 auto result2 = std::min_element( unprocessedElements_.begin(), unprocessedElements_.end(), [](TElement a, TElement b) { return a.Value() < b.Value(); } );
      |                                     ^
/Users/fwegner/Documents/Repositories/Public/EGOA/egoa/tests/DataStructures/Container/TestBucket.cpp:429:17: note: in instantiation of member function 'egoa::Bucket<egoa::BinaryHeap<egoa::BucketElement<long long>>>::Optima' requested here
  429 |         bucket_.Optima();;
      |                 ^
1 warning and 1 error generated.