Enable Tests (#18)
Enable TestBound in the CMakeFile of the test folder. In this version, we duplicate the CMake and CMake builds to download the Google Test Framework. This is required due to the fact that with the current option ExternalProject_Add the external project is only downloaded and installed during the first CMake build. We will change this in another PR to align it with the framework Eigen.

Tests that work on linux "obviously" do not work always with windows ¯_(ツ)_/¯, e.g., in debug mode.

The above test fail was due to the fact that (.*) regular expression is not supported, but .* is. The issue is only happening on Windows. In addition, the message looks a little bit different on Windows compared to Unix systems. The output differs in "inside Bound.\n Condition" (Unix) from "inside egoa::Bound::Bound.\n Condition" (Windows).

Commits:
* Enable TestBound in the CMakeFile
* Add TestBound testcases
* Remove Gurobi Library from TestBound
* Check whether Windows and MacOS find the include with that file
* Replace find_package with own find CMake for Google Testframework
* Downloads need an initial build then the data is on the disk
   Why:
           * add subdirectory in CMake requires the CMakeFile that is not downloaded yet
* Check sudo
* The error in the tests is due to wrong runtime library
* Does DLL works
* Check without debug
* Resolve libcpmt.lib(StlLCMapStringW.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in TestBound.obj [D:\a\egoa\egoa\build\tests\TestBound.vcxproj]
      See note in: https://cmake.org/cmake/help/latest/variable/CMAKE_MSVC_RUNTIME_LIBRARY.html#variable:CMAKE_MSVC_RUNTIME_LIBRARY
* Fix a label mistake
* Add more verbose to the test output to understand what is going on
* Check if differentiation is necessary between Debug and Release
* Follow the error given in Windows debug death test "')' is unsupported"
        D:\a\egoa\egoa\external\GoogleTestFramework\googletest\src/gtest-port.cc(844): error: Failed
        Syntax error at index 42 in simple regular expression "(.*) assertion failed at (.*)Bound.hpp:(.*) inside Bound.
        Condition: minimum_ <= maximum_": ')' is unsupported.

        Running main() from D:\a\egoa\egoa\external\GoogleTestFramework\googletest\src\gtest_main.cc
        D:\a\egoa\egoa\tests\DataStructures\TestBound.cpp(70): error: Death test: {egoa::Bound<> bound (3,1);}
                Result: died but not with expected error.
        Expected: contains regular expression "(.*) assertion failed at (.*)Bound.hpp:(.*) inside Bound.\n Condition: minimum_ <= maximum_"
        Actual msg:
        [  DEATH   ] USAGE assertion failed at D:\a\egoa\egoa\include\DataStructures/Bound.hpp:48 inside egoa::Bound<double>::Bound.
        [  DEATH   ]  Condition: minimum_ <= maximum_

        [  FAILED  ] TestBound.DeathTest (146 ms)
* The output differs in "inside Bound.\n Condition" from "inside egoa::Bound<double>::Bound.\n Condition".
 D:\a\egoa\egoa\tests\DataStructures\TestBound.cpp(70): error: Death test: {egoa::Bound<> bound (3,1);}
                Result: died but not with expected error.
                Expected: contains regular expression ".* assertion failed at .*Bound.hpp:.* inside Bound.\n Condition: minimum_ <= maximum_"
        Actual msg:
        [  DEATH   ] USAGE assertion failed at D:\a\egoa\egoa\include\DataStructures/Bound.hpp:48 inside egoa::Bound<double>::Bound.
        [  DEATH   ]  Condition: minimum_ <= maximum_