Add a flag to solve the C1128 error Windows-Debug specific
What?
D:\a\egoa\egoa\tests\DataStructures\Graphs\TestGraph.cpp : fatal  error C1128: number of sections exceeded object file format limit: compile with /bigobj [D:\a\egoa\egoa\build\tests\TestGraph.vcxproj]

Changes to be committed:
	modified:   cmake/CompilerConfiguration.cmake